version: 1.0.0

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
